# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows 2019

steps:
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproject'
    displayName: 'Restore Nuget package'

-
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproject'
    arguments: '--no-restore'
  displayName : 'Build project'

- task: DotNetCoreCLI@2
  inputs:
      command: 'test'
      projects: '**/*Test.csproject'
  displayName : 'Run Tests'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects : '**/CustmourApi.csproject'
    arguments : '--configuration $(buildconfiguration) --no-restore'
    modifyoutputpath: false
    displayName :'publish customer API'


   
